name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, immortalwrt]

    steps:
      - name: Check Runner
        run: |
          echo "===== HOST ====="
          hostname

          echo
          echo "===== CPU ====="
          nproc
          lscpu | grep "Model name"

          echo
          echo "===== MEMORY ====="
          free -h

          echo
          echo "===== DISK ====="
          df -h /
